- name: Deploy Nginx
  hosts: localhost
  become: true
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Display Nginx server IP
      debug:
        var: ansible_default_ipv4.address

    - name: Verify Nginx deployment
      uri:
        url: "http://{{ ansible_default_ipv4.address }}"
        return_content: yes
      register: response

    - name: Show Nginx landing page
      debug:
        var: response.content
